FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code

COPY . /app
# Expose the port of Streamlit
EXPOSE 8501

# Start command
CMD ["streamlit", "run", "src/ui/streamlit_app.py", "--server.address=0.0.0.0"]