FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente

COPY . /app
# Exponer el puerto de Streamlit
EXPOSE 8501

# Comando de inicio
CMD ["streamlit", "run", "src/ui/streamlit_app.py", "--server.address=0.0.0.0"]